# End your baseURL with a `/` trailing slash, e.g. `https://example.com/`.
baseURL = "https://owlinux1000.github.io/blog/"

languageCode = "en-us"
title = "$ make life"
# theme = "one"
theme = "hugo-flex"
publishDir = "docs"

# Chroma Syntax Highlighting
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "pygments"
