# End your baseURL with a `/` trailing slash, e.g. `https://example.com/`.
baseURL = "https://owlinux1000.github.io/blog/"

languageCode = "en-us"
title = "OwLinux1000's Blog"
theme = "one"
publishDir = "docs"

# Chroma Syntax Highlighting
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "pygments"

[params]
    navigation = ["archives.md", "about.md"]

